name: Update Analytics Data

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install google-analytics-data

    - name: Authenticate with Google
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Fetch analytics data
      env:
        GA_PROPERTY_ID: ${{ secrets.GA_PROPERTY_ID }}
      run: python fetch_analytics.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add data/analytics.json
        git commit -m 'Update analytics data' || echo "No changes to commit"
        git push
